# Generated by Django 4.0.4 on 2022-07-05 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_delete_contacto_blog_titulo_nuevo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo_nuevo',
            field=models.CharField(max_length=1000),
        ),
    ]
