# Generated by Django 4.0.4 on 2022-07-05 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_blog_creado_alter_blog_titulo_nuevo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='creado',
            new_name='fecha',
        ),
    ]
