# Generated by Django 4.0.4 on 2022-07-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_blog_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='titulo_nuevo',
            new_name='titulo_de_pagina',
        ),
    ]
