# Generated by Django 4.0.4 on 2022-07-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0008_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pagina_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
